### ISSUE TITLE
Investigate and fix unicode decode error.

### ISSUE THREAD

**Issue by EugeneLoy** [EugeneLoy/coq_jupyter#21]
Relevant jupyter notebook log part:
<pre>
[IPKernelApp] execute_request: {'header': {'msg_id': '3c72a4e1fdd541db87b88b78326e9016', 'username': 'username', 'session': '9188abbfcd2041598d7e5ac632138cc1', 'msg_type': 'execute_request', 'version': '5.2', 'date': datetime.datetime(2019, 1, 11, 18, 10, 34, 571984, tzinfo=tzlocal())}, 'msg_id': '3c72a4e1fdd541db87b88b78326e9016', 'msg_type': 'execute_request', 'parent_header': {}, 'metadata': {}, 'content': {'code': 'Reset Initial.\n\nDefinition not(p : Prop) := p -> False.\n\nNotation "~ x" := (not x) : type_scope.\n', 'silent': False, 'store_history': True, 'user_expressions': {}, 'allow_stdin': True, 'stop_on_error': True}, 'buffers': []}
[IPKernelApp] Processing 'execute_request', code:
'Reset Initial.\n\nDefinition not(p : Prop) := p -> False.\n\nNotation "~ x" := (not x) : type_scope.\n'

[D 18:10:34.575 NotebookApp] activity on be361ed1-9fc2-4bc8-a9cf-6e2ba09774bb: status
[D 18:10:34.576 NotebookApp] activity on be361ed1-9fc2-4bc8-a9cf-6e2ba09774bb: execute_input
[IPKernelApp] expecting coqtop prompt
[IPKernelApp] coqtop prompt: <_sre.SRE_Match object; span=(2, 35), match='<prompt>Coq < 59 || 0 < </prompt>'>
[IPKernelApp] coqtop output (raw): '\r\n'
[IPKernelApp] coqtop output (simplified): ''
[IPKernelApp] coqtop output contains error message: False
[IPKernelApp] expecting coqtop prompt
[IPKernelApp] coqtop prompt: <_sre.SRE_Match object; span=(26, 59), match='<prompt>Coq < 60 || 0 < </prompt>'>
[IPKernelApp] coqtop output (raw): '     = 433\r\n     : nat\r\n\r\n'
[IPKernelApp] coqtop output (simplified): '= 433\n     : nat'
[IPKernelApp] coqtop output contains error message: False
[IPKernelApp] expecting coqtop prompt
[IPKernelApp] ERROR | Error during evaluating code:
''Reset Initial.\n\nDefinition not(p : Prop) := p -> False.\n\nNotation "~ x" := (not x) : type_scope.\n''
Traceback (most recent call last):
  File "/workspace/coq_jupyter/coq_jupyter/kernel.py", line 253, in do_execute
    result = self._coqtop.eval(code)
  File "/workspace/coq_jupyter/coq_jupyter/kernel.py", line 96, in eval
    (prompt_match, raw_output, simplified_output, error_message) = self._expect_coqtop_prompt()
  File "/workspace/coq_jupyter/coq_jupyter/kernel.py", line 153, in _expect_coqtop_prompt
    self._coqtop.expect(PROMPT, None)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/spawnbase.py", line 178, in read_nonblocking
    s = self._decoder.decode(s, final=False)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 70: invalid start byte
[IPKernelApp] {'header': {'version': '5.3', 'date': datetime.datetime(2019, 1, 11, 18, 10, 34, 637871, tzinfo=datetime.timezone.utc), 'session': '9be71e9c-1c7c621c7419ad2fdaaaa5ea', 'username': 'username', 'msg_type': 'execute_reply', 'msg_id': '469f489d-98a7b265dc59749039f99b60'}, 'msg_id': '469f489d-98a7b265dc59749039f99b60', 'msg_type': 'execute_reply', 'parent_header': {'msg_id': '3c72a4e1fdd541db87b88b78326e9016', 'username': 'username', 'session': '9188abbfcd2041598d7e5ac632138cc1', 'msg_type': 'execute_request', 'version': '5.2', 'date': datetime.datetime(2019, 1, 11, 18, 10, 34, 571984, tzinfo=tzlocal())}, 'content': {'status': 'error', 'ename': 'UnicodeDecodeError', 'evalue': "UnicodeDecodeError('utf-8', b'\\r\\n<prompt>Coq < 61 || 0 < </prompt>\\r\\n<prompt>Coq < 62 || 0 < </prompt>\\xfeToplevel input, characters 1205-1244:\\r\\n Warning: Notation ~ _ was already used in scope type_scope\\r\\n [notation-overridden,parsing]\\xff\\r\\n\\r\\n<prompt>Coq < 63 || 0 < </prompt>', 70, 71, 'invalid start byte')", 'traceback': []}, 'metadata': {'started': datetime.datetime(2019, 1, 11, 18, 10, 34, 573802, tzinfo=datetime.timezone.utc)}, 'tracker': <zmq.sugar.tracker.MessageTracker object at 0x7f24ea081f60>}
[IPKernelApp] Finishing abort
</pre>

**Comment by EugeneLoy** [comment]
Cell code that triggers the message:
<pre>
Reset Initial.
Definition not(p : Prop) := p -> False.
Notation "~ x" := (not x) : type_scope.
</pre>

**Comment by EugeneLoy** [comment]
Attaching reproducing this issue in coqtop:
<pre>
root@26533ca00a7f:/# coqtop -emacs -quiet -l test.v > test.out 2>&1 ; cat test.out
�File "/test.v", line 6, characters 0-39:
 Warning: Notation ~ _ was already used in scope type_scope
 [notation-overridden,parsing]�
Error during initialization:
File "/test.v", line 8, characters 0-5:
Anomaly: Uncaught exception CErrors.Quit. Please report at
http://coq.inria.fr/bugs/.
</pre>

[test.zip](https://github.com/EugeneLoy/coq_jupyter/files/2751061/test.zip)
